import "./globals.css";
import NavBar from "@/app/components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
